# Установка зависимостей
install:
	@echo "Установка зависимостей..."
	pip install -r requirements.txt

# Запуск тестов
test:
	@echo "Запуск тестов..."
	python3 -m unittest discover tests


all: install test